# membuat vector menggunakan function c(value)
# step 1 buat vector dengan value buku, bolpoin, penghapus di ...1...
# step 2 buat vector dengan value 3000, 1500, 500 di ...2... 
# step 3 ubah ...3... menggunakan function names()

barang <- ...1...
prices <- ...2...

...3...(prices) <- barang
prices