# step 1 import library tidyverse di ...1...
# step 2 panggil function tibble() di ...2...
# step 3 isikan dengan variable "sekolah" di ...3...
# step 4 isi dengan value "SD, SMP, SMA" di ...4...
# step 5 isi dengan tahun lulus masing-masing tingkat di ...5...
# step 6 panggil variable NRP untuk mengecek hasil data
library(...1...)

NRP <- ...2...(
  ...3... = c(...4...),
  tahunLulus = c(...5...)
)
...6...